[package]
name = "rrl"
version = "0.1.0"
authors = ["MouseProducedGames"]
edition = "2018"

[dependencies]
crossterm = "0.6.0"
crossterm_cursor = "0.1.0"
crossterm_input = "0.1.0"
crossterm_screen = "0.1"
rand = "0.6"
specs = "0.14.3"
